spring:
  application:
    name: collect
  datasource:
    url: jdbc:mysql://localhost:3306/le?allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.it.common.entity


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true  # ???????
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8082

