spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true  # 避免使用主机名
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8080
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
