#spring.application.name=common
spring:
  application:
    name: common

  datasource:
    #    url: jdbc:mysql://47.108.105.205:3306/elm_second?allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #    username: root
    #    password: hjdhjd
    url: jdbc:mysql://localhost:3306/le?allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
